name: sports-betting-ml
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - requests
  - pip:
      - kagglehub
      - xgboost
      - schedule
      - kaggle